import logging
from pathlib import Path
from typing import Optional, Dict, Any, List
from src.tie.memory_manager import MemoryManager

logger = logging.getLogger(__name__)

class HandoffGenerator:
    def __init__(self, memory_manager: Optional[MemoryManager] = None):
        self.memory_manager = memory_manager or MemoryManager()

    def generate_handoff_file(self, 
                              output_path: Path, 
                              work_id: Optional[str] = None, 
                              genre: Optional[str] = None, 
                              user_id: Optional[str] = None) -> str:
        """
        Generate a reusable translation_handoff.md containing the glossary, characters, 
        style profile, decisions, known issues, and continuation instructions.
        """
        work_val = work_id or "default_work"
        genre_val = genre or "literary"
        user_val = user_id or "default_user"
        
        # 1. Retrieve all memory items
        global_items = self.memory_manager.get_memory_items("global")
        genre_items = self.memory_manager.get_memory_items("genre", scope_id=genre_val)
        work_items = self.memory_manager.get_memory_items("work", scope_id=work_val)
        user_items = self.memory_manager.get_memory_items("user", scope_id=user_val)
        
        # 2. Extract specific segments
        # Characters & Terms
        characters = []
        glossary_terms = []
        for item in work_items:
            itype = item.get("type")
            key = item.get("key")
            val = item.get("value")
            notes = item.get("notes", "")
            
            if itype == "character_info":
                characters.append(f"- **{key}**: {val}" + (f" ({notes})" if notes else ""))
            elif itype in ["terminology", "glossary"]:
                glossary_terms.append(f"- **{key}**: {val}" + (f" ({notes})" if notes else ""))

        # Decisions
        decisions = []
        for item in global_items + genre_items + work_items + user_items:
            itype = item.get("type")
            key = item.get("key")
            val = item.get("value")
            scope = item.get("scope")
            
            if itype in ["phrasal_verb", "idiom", "correction_pattern"]:
                decisions.append(f"- [{scope.upper()}] **{key}** -> *{val}* (Type: {itype})")

        # Style Notes
        style_notes = []
        style_profile = self.memory_manager.read_style_profile(work_val)
        if style_profile:
            style_notes.append(style_profile)
            
        for item in genre_items + user_items + work_items:
            if item.get("type") == "style_rule":
                key = item.get("key", "")
                val = item.get("value", "")
                style_notes.append(f"- {key}: {val}")

        # Known Issues / Pitfalls
        known_issues = []
        for item in global_items + genre_items + work_items + user_items:
            if item.get("type") == "correction_pattern":
                key = item.get("key")
                val = item.get("value")
                notes = item.get("notes", "")
                known_issues.append(f"- Avoid translating '{key}' literally. Preferred: '{val}'" + (f" (Issue: {notes})" if notes else ""))

        # Fallback loads from static data files if memory is empty
        if not glossary_terms:
            from src.core.config import Config
            import json
            # Try to load default genre glossary
            _, path = Config.get_genre_paths(genre_val)
            if path.exists():
                try:
                    with open(path, "r", encoding="utf-8") as f:
                        static_glossary = json.load(f)
                        for term_obj in static_glossary:
                            glossary_terms.append(f"- **{term_obj.get('term')}**: {term_obj.get('translation')}" + (f" ({term_obj.get('notes')})" if term_obj.get('notes') else ""))
                except:
                    pass

        # 3. Compile Handoff Markdown
        lines = [
            f"# Translation Handoff: {work_val.upper()}",
            "",
            "This document is a reusable translation handoff generated by TransCraft TIE v0.1. "
            "It contains accumulated translation intelligence to maintain consistency across LLMs.",
            "",
            "## Project Context",
            f"- **Work ID:** {work_val}",
            f"- **Genre:** {genre_val}",
            f"- **User Context:** {user_val}",
            "",
            "## Active Glossary & Characters"
        ]
        
        if characters:
            lines.append("### Characters:")
            lines.extend(characters)
            lines.append("")
            
        if glossary_terms:
            lines.append("### Key Terminology:")
            lines.extend(glossary_terms)
        else:
            lines.append("*No specific glossary terms extracted yet.*")
        lines.append("")

        lines.append("## Style Profile & Rules")
        if style_notes:
            lines.extend(style_notes)
        else:
            lines.append("- Adhere to natural Target Language rhythm and style standards.")
        lines.append("")

        lines.append("## Translation Decisions")
        if decisions:
            lines.extend(decisions)
        else:
            lines.append("*No dynamic translation decisions recorded yet.*")
        lines.append("")

        lines.append("## Known Issues & Pitfalls to Avoid")
        if known_issues:
            lines.extend(known_issues)
        else:
            lines.append("- Avoid literal translations of idioms and phrasal verbs.")
            lines.append("- Avoid repeating common EN->TR structural transformations verbatim.")
        lines.append("")

        lines.extend([
            "## Continuation Instructions",
            "To continue translating this work:",
            "1. Read the character names and term mappings under **Active Glossary & Characters** to maintain naming consistency.",
            "2. Strictly follow the rules in **Style Profile & Rules** to preserve the tone.",
            "3. Look out for the literal translation traps listed under **Known Issues & Pitfalls to Avoid**.",
            "4. Apply the phrase transformations detailed in **Translation Decisions**."
        ])

        handoff_content = "\n".join(lines)
        
        # Write to file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(handoff_content)
            logger.info(f"Handoff generated successfully at {output_path}")
        except Exception as e:
            logger.error(f"Error saving handoff file {output_path}: {e}")
            raise e
            
        return handoff_content
